### ISSUE TITLE
Value supplied for Accept header is not supported.

### ISSUE THREAD

**Issue by TerriblyVexed** [brianpos/UploadFIG#1]
I'm getting this error on every file in the IG. Do I need to disable authentication to use this tool?
I'm trying to use this on Azure API for Fhir.

**Comment by brianpos** [comment]
Sorry this has taken so long to get back to.
Now that it's switched over to a commandline tool that you don't need to build (dotnet tool install etc)
And there is a parameter you can use to provide the destination server headers.
--destinationServerHeaders or -dh "Authentication: Bearer xxxxxxxxxxx"

**Comment by brianpos** [comment]
The message is on the accept header, not the authorization header.
Maybe try the `-df json` parameter?

**Comment by enjoysparkling** [comment]
Thank you, that did the trick!  It did require -dh "_Authorization_: Bearer xxx" (not Authentication).  But I did not have to do the az login.

So, to get this to work on Azure FHIR service, I ran:
```
UploadFIG -pid hl7.fhir.us.core -pv 6.0.0 -c -d https://<my_server>.fhir.azurehealthcareapis.com -df json -dh "Authorization:Bearer xxxx" --verbose
```
